package com.fa.domain.enumeration;

/**
 * The OrderState enumeration.
 */
public enum OrderState {
    SUBMITTED,FAILED,APPROVED,PROCESSING,PROCESSED,AMENDED,FAILED_APPROVAL,FAILED_AMENDMENT,PENDING_CUSTOMER_ACTION,PENDING_MERCHANT_ACTION,NO_PENDING_ACTION
}
